# Library updates
GROUP=io.rekast
POM_ARTIFACT_ID=momo-api-sdk
VERSION_NAME=0.2.1-SNAPSHOT
POM_PACKAGING=aar

POM_NAME=MTN MOMO API SDK
POM_DESCRIPTION=Kotlin Multiplatform (KMP) library that simplifies integration of MTN Mobile Money (MOMO) services into Android and JVM applications, providing secure user authentication, balance inquiries, payment requests, disbursements, and refunds.
POM_INCEPTION_YEAR=2023
POM_URL=https://github.com/re-kast/android-mtn-momo-api-sdk

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/re-kast/android-mtn-momo-api-sdk
POM_SCM_CONNECTION=scm:git:git@github.com:re-kast/android-mtn-momo-api-sdk.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:re-kast/android-mtn-momo-api-sdk.git

POM_DEVELOPER_ID=dubdabasoduba
POM_DEVELOPER_NAME=Benjamin Mwalimu
POM_DEVELOPER_URL=https://github.com/dubdabasoduba
POM_DEVELOPER_EMAIL=dubdabasoduba@gmail.com

